### ISSUE TITLE
Can I get banned from using this?

### ISSUE THREAD

**Issue by ferivoq** [SuppliedOrange/VALORANT-Instalocker#10]
Can I get banned for using this tool?
I mean this doesn't seem too legal.

**Comment by SuppliedOrange** [comment]
You can get banned from using this if:

1: You set lock delay to 0 or somehow managed to spam their API

2: You tell people you have an instalocker and you get reported for it.

3: Riot bans the release executable on this but they haven't because a project of this scale and magnitude won't interest them.

Otherwise, no.
